[package]
name = "kite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
bevy_egui = "0.21.0"
bevy_asset_loader = "0.17.0"
bevy-inspector-egui = "0.19.0"
#bevy_xpbd_2d = "0.2"


